language: node_js
sudo: required
dist: trusty


node_js:
  - '5.10'

addons:
  firefox: latest
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

      - mesa-utils
      - xvfb
      - libosmesa6

      - libgif-dev
      - libpng-dev

      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libxxf86vm-dev
      - libxrandr-dev

cache:
  directories:
    - node_modules

before_install:
  - npm prune

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - npm install
  - npm run build
  - npm run test
